name: Auto-Deploy Main Branch to VPS

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]

jobs:
  test:
    name: Auto-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v3
      - name: Execute Auto-Deploy Query
        id: query
        uses: ./
        with:
          url: ${{ secrets.AUTO_DEPLOY_HOST }}
      - name: Print the response status
        run: echo ${{ steps.query.outputs.status }}
